name: Buildozer Android APK

on:
  push:
    branches:
      - main  # أو أي فرع رئيسي تستخدمه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Buildozer
        uses: abrown/buildozer-action@v1
        
        id: buildozer
        with:
          command: buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
