name: Build APK with Buildozer

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with buildozer
        uses: kivy/buildozer-action@master
        with:
          command: buildozer android debug
